// npm run i18n — extracts every translatable string into i18n/odoo_debug.pot and merges it into i18n/<lang>.po.
//   JS:   _t('literal', …) and N_('literal') (template literals / variables are not extracted: always pass a literal)
//   HTML: elements with data-i18n="text,title,…" (the English text / attribute values are the msgids)
// Existing translations are kept, new strings get an empty msgstr (en.po: msgstr = msgid), removed strings are dropped.
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, relative } from 'node:path';
import { parsePo, LANGS } from '../extension/src/shared/i18n.js';

const ROOT = join(import.meta.dirname, '..', 'extension');
const DIR = join(ROOT, 'i18n');
const POT = join(DIR, 'odoo_debug.pot');

const files = (dir) => readdirSync(dir, { withFileTypes: true }).flatMap((d) =>
  d.isDirectory() ? files(join(dir, d.name)) : /\.(js|html)$/.test(d.name) ? [join(dir, d.name)] : []).sort();
// ponytail: literals are decoded with Function (our own source only), exact JS escape semantics for free.
const decode = (lit) => new Function(`return ${lit}`)();
const lineOf = (text, i) => text.slice(0, i).split('\n').length;

const found = new Map(); // msgid → ["file:line", …] in source order
const add = (msgid, ref) => { if (!found.has(msgid)) found.set(msgid, []); found.get(msgid).push(ref); };

for (const f of files(join(ROOT, 'src'))) {
  const text = readFileSync(f, 'utf8');
  const rel = relative(ROOT, f);
  if (f.endsWith('.js')) {
    for (const m of text.matchAll(/(?<![\w.$])(?:_t|N_)\(\s*('(?:[^'\\\n]|\\.)*'|"(?:[^"\\\n]|\\.)*")/g)) add(decode(m[1]), `${rel}:${lineOf(text, m.index)}`);
  } else {
    for (const m of text.matchAll(/<\w+\b([^>]*)\bdata-i18n="([^"]+)"([^>]*)>([^<]*)/g)) {
      const attrs = m[1] + m[3];
      for (const what of m[2].split(',')) {
        const v = what === 'text' ? m[4].trim() : attrs.match(new RegExp(`\\b${what}="([^"]*)"`))?.[1];
        if (v) add(v, `${rel}:${lineOf(text, m.index)}`);
      }
    }
  }
}

const q = (s) => JSON.stringify(s); // PO and JSON share the escapes we need (\" \\ \n \t)
const header = (lang) => [
  'msgid ""', 'msgstr ""',
  q('Project-Id-Version: Odoo Debug\n'), q('PO-Revision-Date: \n'), q('Last-Translator: \n'), q('Language-Team: \n'),
  q(`Language: ${lang}\n`), q('MIME-Version: 1.0\n'), q('Content-Type: text/plain; charset=UTF-8\n'), q('Content-Transfer-Encoding: 8bit\n'), '',
].join('\n');
const body = (tr) => [...found].map(([id, refs]) => `${refs.map((r) => `#: ${r}`).join('\n')}\nmsgid ${q(id)}\nmsgstr ${q(tr(id))}\n`).join('\n');

writeFileSync(POT, `# Odoo Debug — translation template, generated by \`npm run i18n\`: do not edit by hand.\n${header('')}\n${body(() => '')}`);
console.log(`${relative(ROOT, POT)}: ${found.size} strings`);

const holes = (s) => (s.match(/%s/g) || []).length;
for (const lang of Object.keys(LANGS)) {
  const file = join(DIR, `${lang}.po`);
  const old = existsSync(file) ? parsePo(readFileSync(file, 'utf8')) : new Map();
  const tr = (id) => old.get(id) || (lang === 'en' ? id : '');
  writeFileSync(file, `# Odoo Debug — ${LANGS[lang]}\n${header(lang)}\n${body(tr)}`);
  const missing = [...found.keys()].filter((id) => !tr(id));
  const bad = [...found.keys()].filter((id) => tr(id) && holes(tr(id)) !== holes(id));
  const dropped = [...old.keys()].filter((id) => !found.has(id));
  console.log(`${relative(ROOT, file)}: ${found.size - missing.length}/${found.size} translated`
    + (dropped.length ? `, ${dropped.length} obsolete dropped` : '')
    + (bad.length ? `\n  %s count mismatch: ${bad.map(q).join(', ')}` : '')
    + (missing.length ? `\n  untranslated: ${missing.map(q).join(', ')}` : ''));
}
